### ISSUE TITLE
Android sources help

### ISSUE THREAD

**Issue by Athwale** [andylin-hao/AOSP_Docker_Build#1]
Hello, I would like to use your docker image to build Android for x86, but I am doing it the first time and do not know much about it yet.

Do you know where I can download the sources for "$ANDROID_BUILD_TOP is the root directory of your AOSP/Android-x86 sources."
Ideally for older Android like 7-8?

Thanks.

**Comment by andylin-hao** [comment]
You can find the instructions here: https://www.android-x86.org/source.html.

Basically just do the following:
```bash
mkdir android
cd android
# Change nougat-x86 (Android 7.1) to other branches (see the branch names in the link above) if you want
repo init -u http://scm.osdn.net/gitroot/android-x86/manifest -b nougat-x86
repo sync --no-tags --no-clone-bundle
```
You'll need the `repo` tool for the cmds. Installation guide is here: https://gerrit.googlesource.com/git-repo/+/HEAD/README.md.

**Comment by Athwale** [comment]
I am trying to do that, but I get this:
```
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 158, done
remote: Finding sources: 100% (13/13)
remote: Total 13 (delta 4), reused 12 (delta 4)

manifests:
fatal: unable to access 'http://scm.osdn.net/gitroot/android-x86/manifest/': Failed to connect to scm.osdn.net port 80 after 132992 ms: Couldn't connect to server
manifests: sleeping 4.0 seconds before retrying
```

Is it working for you?

**Comment by andylin-hao** [comment]
Yeah, their OSDN git server is down. You can try their sourceforge repo instead: `repo init -u https://git.code.sf.net/p/android-x86/manifest -b nougat-x86`.

**Comment by Athwale** [comment]
That is working. Thank you very much!

Can I suggest you add this information where to get the sources to your readme file?

**Comment by andylin-hao** [comment]
Sure, I just did in 59787af.
